### ISSUE TITLE
Tie Situation

### ISSUE THREAD

**Issue by amstars** [itsbspoke/blue-diamond-awards#19]
Everything looks good for the "Winners" page, except the slim renders differently and it won't let me format for two winners in one category.

**Comment by scpaye506** [comment]
Sorry, there wasn't really a design for a tie. Here is a possible fix though that I think would work and still look ok.

In the _winners_categoires.html.slim file you can do this:

https://gist.github.com/scpaye506/60250621630e8616e36f

and in the winners.yaml file, for whatever category has 2 winners, you can do this:

https://gist.github.com/scpaye506/dbe551ab006e82e1178a

**Comment by amstars** [comment]
Thanks, @scpaye506! I don't ever work in slim so you've been a lifesaver!
